// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOVScLq6zH9YDscJgG3S8-6jzGZpxQhOg',
    appId: '1:403856486737:web:fc2c4a18adc314ef2ca370',
    messagingSenderId: '403856486737',
    projectId: 'prime-b09b7',
    authDomain: 'prime-b09b7.firebaseapp.com',
    storageBucket: 'prime-b09b7.appspot.com',
    measurementId: 'G-C6YE6MS9R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiyVwkmVNRtxLXDXRlN5ZM1616p0odSuA',
    appId: '1:403856486737:android:ce504a7a41281c162ca370',
    messagingSenderId: '403856486737',
    projectId: 'prime-b09b7',
    storageBucket: 'prime-b09b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46s0Jf3i0uxnm4eunWmvPKjV4AZd9Nk4',
    appId: '1:403856486737:ios:19e33ab6b2d9836a2ca370',
    messagingSenderId: '403856486737',
    projectId: 'prime-b09b7',
    storageBucket: 'prime-b09b7.appspot.com',
    iosBundleId: 'com.example.prime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA46s0Jf3i0uxnm4eunWmvPKjV4AZd9Nk4',
    appId: '1:403856486737:ios:a555f577781f7aa82ca370',
    messagingSenderId: '403856486737',
    projectId: 'prime-b09b7',
    storageBucket: 'prime-b09b7.appspot.com',
    iosBundleId: 'com.example.prime.RunnerTests',
  );
}
